
package service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "EtudiantServiceService", targetNamespace = "http://service/", wsdlLocation = "http://localhost:8085/EtudiantWs?wsdl")
public class EtudiantServiceService
    extends Service
{

    private final static URL ETUDIANTSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException ETUDIANTSERVICESERVICE_EXCEPTION;
    private final static QName ETUDIANTSERVICESERVICE_QNAME = new QName("http://service/", "EtudiantServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8085/EtudiantWs?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ETUDIANTSERVICESERVICE_WSDL_LOCATION = url;
        ETUDIANTSERVICESERVICE_EXCEPTION = e;
    }

    public EtudiantServiceService() {
        super(__getWsdlLocation(), ETUDIANTSERVICESERVICE_QNAME);
    }

    public EtudiantServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ETUDIANTSERVICESERVICE_QNAME, features);
    }

    public EtudiantServiceService(URL wsdlLocation) {
        super(wsdlLocation, ETUDIANTSERVICESERVICE_QNAME);
    }

    public EtudiantServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ETUDIANTSERVICESERVICE_QNAME, features);
    }

    public EtudiantServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EtudiantServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Etudiant
     */
    @WebEndpoint(name = "EtudiantPort")
    public Etudiant getEtudiantPort() {
        return super.getPort(new QName("http://service/", "EtudiantPort"), Etudiant.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Etudiant
     */
    @WebEndpoint(name = "EtudiantPort")
    public Etudiant getEtudiantPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service/", "EtudiantPort"), Etudiant.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ETUDIANTSERVICESERVICE_EXCEPTION!= null) {
            throw ETUDIANTSERVICESERVICE_EXCEPTION;
        }
        return ETUDIANTSERVICESERVICE_WSDL_LOCATION;
    }

}
