
package service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Etudiant", targetNamespace = "http://service/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Etudiant {


    /**
     * 
     * @param somme
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "lamoyenne", targetNamespace = "http://service/", className = "service.Lamoyenne")
    @ResponseWrapper(localName = "lamoyenneResponse", targetNamespace = "http://service/", className = "service.LamoyenneResponse")
    @Action(input = "http://service/Etudiant/lamoyenneRequest", output = "http://service/Etudiant/lamoyenneResponse")
    public double lamoyenne(
        @WebParam(name = "somme", targetNamespace = "")
        double somme);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<service.Etudiant_Type>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listEtudiant", targetNamespace = "http://service/", className = "service.ListEtudiant")
    @ResponseWrapper(localName = "listEtudiantResponse", targetNamespace = "http://service/", className = "service.ListEtudiantResponse")
    @Action(input = "http://service/Etudiant/listEtudiantRequest", output = "http://service/Etudiant/listEtudiantResponse")
    public List<Etudiant_Type> listEtudiant(
        @WebParam(name = "arg0", targetNamespace = "")
        Long arg0);

    /**
     * 
     * @param matricule
     * @return
     *     returns service.Etudiant_Type
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "unEtudiant", targetNamespace = "http://service/", className = "service.UnEtudiant")
    @ResponseWrapper(localName = "unEtudiantResponse", targetNamespace = "http://service/", className = "service.UnEtudiantResponse")
    @Action(input = "http://service/Etudiant/unEtudiantRequest", output = "http://service/Etudiant/unEtudiantResponse")
    public Etudiant_Type unEtudiant(
        @WebParam(name = "matricule", targetNamespace = "")
        Long matricule);

}
